name: Assessment

on:
    pull_request:
        branches: [master, main]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Install dependencies
          id: dependencies
          run: dart pub get
          continue-on-error: true
 

        - name: Test
          id: tests
          run: dart pub global activate junitreport
               dart test simple_test.dart --reporter json > example.jsonl 
               dart pub global run junitreport:tojunit --input example.jsonl --output report.xml
          continue-on-error: true
        - name:  Dump GitHub context
          if: steps.tests.outcome == 'failure'
          id: github_context_step
          run: echo '${{ toJSON(steps.tests.outcome) }}'
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v2.3.1
          with:
             path: report.xml
             if-no-files-found: error
