name: Assessment

on:
    pull_request:
        branches: [master, main]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Install dependencies
          id: dependencies
          run: dart pub get
          continue-on-error: true
 

        - name: Test
          id: tests
          run: dart test
          continue-on-error: true
        - name:  Dump GitHub context
          if: steps.tests.outcome == 'failure'
          id: github_context_step
          run: echo '${{ toJSON(steps.tests.outcome) }}'
